---
- name: Ensure fzf parent directory exists
  ansible.builtin.file:
    path: "{{ fzf_parentdir }}"
    state: directory
    mode: "0750"

- name: Git clone fzf  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ fzf_parentdir }}/fzf"
    depth: 1
    update: true

- name: Install fzf
  ansible.builtin.command:
    cmd: "{{ fzf_parentdir }}/fzf/install --all"
    creates: "{{ fzf_parentdir }}/fzf/bin/fzf"
