---
- name: Ensure fzf parent directory exists
  file:
    path: "{{ fzf_parentdir }}"
    state: directory
    mode: "0750"

- name: Git pull fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ fzf_parentdir }}/fzf"
    depth: 1
    update: true

- name: Install fzf
  ansible.builtin.command: "{{ ansible_env.HOME }}/git/fzf/install --all"
  args:
    creates: "{{ ansible_env.HOME }}/.fzf.zsh"
